### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nozpheratu** [sous-chefs/chef-rvm#362]

**Comment by shafiqissani** [comment]
❓

**Comment by sethfloydjr** [comment]
(Bumpity bump)

**Comment by etki** [comment]
(bumpedous)

**Comment by potato20** [comment]
Yes

**Comment by trinitronx** [comment]
@martinisoft :  If this project is too time consuming for just you, why not [let the community help out](https://felixge.de/2013/03/11/the-pull-request-hack.html).

**Comment by trinitronx** [comment]
Hmm... I missed the details in #354 earlier.  Seems that the plan was to attempt a large refactor which still was a work in progress at last update.  Then, this was to be handed over to the [Sous Chefs](http://sous-chefs.org/) to maintain in their [GitHub Organization](https://github.com/sous-chefs).

In the meantime before I learned of this, I started work on a path towards some minor fixes to support Chef 13.  So far great success on all `test-kitchen` suites except for the `stock-system-and-user` suite.  I believe there is one major hurdle left which is beginning to look a bit tricky due to the [deprecation of `Chef::Mixin::Command`](https://github.com/chef/chef/commit/9c0a6a3775314872c8d3b9c914ba56bbda6c8e1b) ([See also this OHAI-3 note](https://docs.chef.io/deprecations_ohai_run_command_helpers.html)).

The details of this problem were mentioned in #367.  I will continue to try my hand at pulling this sword from the stone... I believe it may be possible, but no guarantees yet.  If I get this working, maybe it helps to keep some backwards compatibility support for Chef <= 13 as opposed to the massive changes in #354.

With enough monkeys on typewriters getting this thing working again just might be possible :smile:

**Comment by damacus** [comment]
Hi there!

we're always looking for people to help out maintain the community cookbooks, it's really the reason sous-chefs exists.

We have a number of generalists in sous-chefs that would love to show some new people around, how  to create the best cookbooks we can, however those generalists often are spread thin and do not know the product which is being automated too well.

With that in mind even if it's just a README update, or typo fix, we would always encourage newcomers to get involved!

**Comment by damacus** [comment]
And yes, it's back alive again 👍
